# Generated by Django 4.2.7 on 2023-12-25 05:41

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_pdffile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=models.FileField(upload_to=main.models.ascii_filename),
        ),
    ]
